### ISSUE TITLE
Problem po aktualizacji do 1.0.1

### ISSUE THREAD

**Issue by Undercore90** [dumbasPL/aero2solver#5]
Witaj,

Chciałbym prosić cię o pomoc w namierzeniu problemu. Wszystko działało dobrze do momentu aktualizacji. Po aktualizacji jakby nic się nie zmieniło, jednak po losowym okresie czasu nagle urządzenie jest offline.

Gdy podjechałem na miejsce i połączyłem się do WiFi od razu wyskoczyła strona logowania do Aero.

Nie zalogowałem się i przeszedłem do maszyny z aero2solver na której wykonane było polecenie:

docker run -d --restart=always --name aero2solver dumbaspl/aero2solver

zalogowałem się i wykonałem polecenie: docker run -it --rm dumbaspl/aero2solver i po sekundzie wyskoczył komunikat, że dostęp został odblokowany i wszystko było ok.

Wyjechałem i po kilku dobrych godzinach sytuacja powtórzyła się.

Chciałbym zebrać logi aby sprawdzić co może powodować problem więc proszę o wskazówki zakupiłem pakiet więc mam ciągle uruchomioną maszynę i dostęp przez Internet ale nie wykonałem polecenia: docker run -it --rm dumbaspl/aero2solver aby nie zakłamać logów.

Jeżeli nie uda się dokopać do powodu błędu proszę o podanie sposobu na instalację i uruchomienie (docker run -d --restart=always --name aero2solver dumbaspl/aero2solver) wersji 1.0,0 być może to rozwiąże mój problem.

**Comment by Undercore90** [comment]
Dodam taki jeszcze log:
ec98d3f304b2   dumbaspl/aero2solver   "/app/aero2solver"   8 days ago   Up 46 hours             aero2solver

A jak wyeksportowałem logi:
`docker logs -t ec98d3f304b2 > logs.txt`

to mam błąd podczas eksportu a log kończy się 08.. 

`error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value`

```
2024-05-08T18:36:05.026023290Z Captcha not required with message: Dostęp do Internetu został odblokowany.
2024-05-08T18:36:15.188999253Z Captcha not required with message: Dostęp do Internetu został odblokowany.
2024-05-08T18:36:25.371725403Z Captcha not required with message: Dostęp do Internetu został odblokowany.
2024-05-08T18:36:35.518937913Z Captcha not required with message: Dostęp do Internetu został odblokowany.
2024-05-08T18:36:45.652268323Z Captcha not required with message: Dostęp do Internetu został odblokowany.
2024-05-08T18:36:55.783763115Z Captcha not required with message: Dostęp do Internetu został odblokowany.
2024-05-08T18:37:05.927065633Z Captcha not required with message: Dostęp do Internetu został odblokowany.
2024-05-08T18:37:16.075905621Z Captcha not required with message: Dostęp do Internetu został odblokowany.
```

**Comment by dumbasPL** [comment]
> Jeżeli nie uda się dokopać do powodu błędu proszę o podanie sposobu na instalację i uruchomienie (docker run -d --restart=always --name aero2solver dumbaspl/aero2solver) wersji 1.0,0 być może to rozwiąże mój problem.

możesz przypiąć wersje obrazu do konkretnego taga: `dumbaspl/aero2solver:sha-aae811b`  (wersja 1.0.0) [pełna lista](https://hub.docker.com/r/dumbaspl/aero2solver/tags)

> [...] wykonałem polecenie: docker run -it --rm dumbaspl/aero2solver [...]
> [...] ale nie wykonałem polecenia: docker run -it --rm dumbaspl/aero2solver [...]

??? masz na myśli `docker rm <id>` w tej drugiej?

> A jak wyeksportowałem logi:
> docker logs -t ec98d3f304b2 > logs.txt

> to mam błąd podczas eksportu a log kończy się 08..

spróbuj
`docker inspect --format='{{.LogPath}}' ec98d3f304b2`
i wyślij ten plik tutaj (możesz zrobić zip albo tar żeby na 100% nic nie zmienić w formatowaniu)

daj też daty kiedy sie popsuło i ile dziłało żebym wiedział czego w logu szukać. Daj też znać czy chce ci sie testować czy nie, jak nie to tylko wyślij log i przypnij sobie wersje na stało.

> Po aktualizacji jakby nic się nie zmieniło, jednak po losowym okresie czasu nagle urządzenie jest offline.

zmiany od 1.0.0:
- [cross compile docker images instead of emulating](https://github.com/dumbasPL/aero2solver/commit/99b4e5d0083f45eff6d1ffc509c5dd2d66601f01)
- [added tests](https://github.com/dumbasPL/aero2solver/commit/1ae0db2388fd3f22d98ad20cacc4d0002b226364)
- [convert to async](https://github.com/dumbasPL/aero2solver/commit/aae811b2c7edd3f8d2e52652e0cedab9098bb608)
- [disable openmp by default, update dependencies](https://github.com/dumbasPL/aero2solver/commit/93d2deb59f319892dbaa8676dcb4979b77733e78)

pierwsze 2 wątpie że coś popsuły, ostatni tak samo bo jak by tak było to pierwszy raz też by sie nie udało rozwiązać po restarcie.

ja bym podejżewał nr 3, szczególnie że używam `#[tokio::main(flavor = "current_thread")]`.
Co jest dziwne bo w teori jeden wątek powinien wystarczyć. gdzieś jest pewnie jakiś deadlock który przydało by się znaleźć ale bez debuggera ani symboli ciężko.

Daj znaś na jakim sprzęcie to odpalasz (architektura i RAM) ale jak masz pełnego dockera to obstawiam że coś mocniejszego niż ram liczony w MB ;)

Sorry za wolną odpowiedź, nie widziłem powiadomienia.

**Comment by Undercore90** [comment]
Hej,

Ciężko mi będzie teraz odpowiedzieć na wszystko bardziej wieczorem ale:

> [...] wykonałem polecenie: docker run -it --rm dumbaspl/aero2solver [...]
> [...] ale nie wykonałem polecenia: docker run -it --rm dumbaspl/aero2solver [...]
> 
> ??? masz na myśli docker rm <id> w tej drugiej?

Chodzi o to, że pierwszy raz jak wystąpiła awaria pojechałem na miejsce zalogowałem się do Proxmox i po prostu użyłem polecenie docker run -it --rm dumbaspl/aero2solver wtedy automatycznie wyświetla się zawartość kontenera i działający skrypt i magicznie jak kliknąłem enter w sekundę obrazek został rozwiązany i Internet wrócił, więc gdy drugi raz go straciłem to już go nie wykonywałem drugi raz więc powinien zostać w takim stanie jak był zamiast tego kupiłem pakiet aby Internet wrócił.

Właśnie sprawdziłem moje aero i pakiet się skończył a nie było prądu więc Proxmox działa 2h i Internet również jest dostępny więc skrypt działa.

Usterka była chyba 11.05.2024  po 1 w nocy niestety ciężko mi się dokopać w powiadomieniach kiedy kamera była offline.
[ec98d3f304b21293dcae03e86cfc6290b183c0216b9a658182dee96e176068ad-json.zip](https://github.com/dumbasPL/aero2solver/files/15330837/ec98d3f304b21293dcae03e86cfc6290b183c0216b9a658182dee96e176068ad-json.zip)

![image](https://github.com/dumbasPL/aero2solver/assets/156170953/aae7b827-6a4d-405b-88e1-805d008ae0b0)

Daj znać czy coś jeszcze potrzebujesz.

**Comment by dumbasPL** [comment]
https://github.com/dumbasPL/aero2solver/releases/tag/v1.1.0

problem był w tym że aero2 o północy resetuje serwery a nie było timeout na połączeniu, trafiłeś na to przypadkiem, nie związane z wersją 1.0.1

jak będą dalej problemy to zrób nowy issue
